In [8]:
import numpy as np # Все функции были взяты с https://numpy.org/doc/stable/index.html , мне удобнее работать с оригинальной документацией , находя функцию , которая мне нужна по поиску в документации

# 1 пункт , среднее арифметическое входного массива .mean()
print("1 пункт:")
# Создаём сам массив
arr = np.array([1,2,3,4,5,6,7,8,9,10])
# Используем дефолтную функцию библиотеки нумпай
mean = np.mean(arr)
print("Среднее арифметическое массива: ", mean, "\n")

1 пункт:
Среднее арифметическое массива:  5.5 



In [9]:
# 2 пункт , всё то же самое , но найти максимальное значение , будем использовать тот же массив что и из пункта 1
print("2 пункт:")
# Создадим переменную amax и поместим в неё максимальное значение массива с помощью функции нампая
maxa = np.amax(arr)
print("Максимальное значение массива:", maxa, "\n")

2 пункт:
Максимальное значение массива: 10 



In [21]:
#3 пункт , инверсия второго , тоесть минимальное значение
print("3 пункт:")
# Также создаём переменную
min = np.amin(arr)
print("Минимальное значение массива:",min, "\n")

3 пункт:
Минимальное значение массива: 1 



In [24]:
#4 пункт , ничего сложного , используем все те же встроенные функции либы
print("4 пункт:")
argmaxa = np.argmax(arr)
print("Индекс максимального элемента массива:", argmaxa, "\n")

4 пункт:
Индекс максимального элемента массива: 9 



In [25]:
#5 пункт , инверсия 4
print("5 пункт:")
argmina = np.argmin(arr)
print("Индекс минимального элемента массива:", argmina, "\n")

5 пункт:
Индекс минимального элемента массива: 0 



In [27]:
#6 пункт , задача немного поменялась и нам нужен массив с отрицательными числами
print("6 пункт:")
arr1 = np.array([1,-2,3,-4,5,-6,7,-8,9,-10])
negative = np.maximum(arr1, 0) # https://numpy.org/doc/stable/reference/generated/numpy.maximum.html , голова взрывается от количества возможных параметров у этой функции , лучше матлаба
print("Заменённый массив , где число < 0 превращается в 0:", "\n", negative)

6 пункт:
Заменённый массив , где число < 0 превращается в 0: 
 [1 0 3 0 5 0 7 0 9 0]


In [14]:
#7 пункт инверсия 6
print("7 пункт:")
poloz = np.minimum(arr1, 0)
print("Заменённый массив , где число > 0 превращается в 0:", "\n", poloz)

7 пункт:
Заменённый массив , где число > 0 превращается в 0: 
 [  0  -2   0  -4   0  -6   0  -8   0 -10]


In [15]:
#8 пункт
print("8 пункт:")
st3 = np.power(arr, 3)
print("Первый массив ,возведённый в 3 степень:","\n", st3, "\n")

8 пункт:
Первый массив ,возведённый в 3 степень: 
 [   1    8   27   64  125  216  343  512  729 1000] 



In [26]:
#9 пункт
print("9 пункт:")
root = np.sqrt(arr)
print("Квадратный корень каждого элемента массива:", "\n", root, "\n")

9 пункт:
Квадратный корень каждого элемента массива: 
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766] 



In [19]:
# 10 пункт
print("10 пункт:")
sm = np.sum(arr1)
print("Сумма элементов массива:", sm)

10 пункт:
Сумма элементов массива: -5
